// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHndxGgRVgoiftNLiKK3QP6Uybcuqcrec',
    appId: '1:77933480849:web:bc2bc0df5c18b36d1fa830',
    messagingSenderId: '77933480849',
    projectId: 'flutter-chat-app-c4a76',
    authDomain: 'flutter-chat-app-c4a76.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c4a76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVmgiRWlqrAhZz02UZbdcmRe5YLUqD7I',
    appId: '1:77933480849:android:491b517785de05c71fa830',
    messagingSenderId: '77933480849',
    projectId: 'flutter-chat-app-c4a76',
    storageBucket: 'flutter-chat-app-c4a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-lYwGDt0gcCInNUfH0KURlqJT2S9iQs',
    appId: '1:77933480849:ios:8eca779dabca696d1fa830',
    messagingSenderId: '77933480849',
    projectId: 'flutter-chat-app-c4a76',
    storageBucket: 'flutter-chat-app-c4a76.appspot.com',
    iosClientId: '77933480849-ua91v6bae5vi4hi2dnj8cjv56k9jqe1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-lYwGDt0gcCInNUfH0KURlqJT2S9iQs',
    appId: '1:77933480849:ios:66e6e81027aae4671fa830',
    messagingSenderId: '77933480849',
    projectId: 'flutter-chat-app-c4a76',
    storageBucket: 'flutter-chat-app-c4a76.appspot.com',
    iosClientId: '77933480849-bq6afv43i2oomtl5no8s95sgep90v943.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
